# -*- coding: utf-8 -*-
"""Word_Guessing_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxQWr0KoPbhokZCnyiGJDXvsFP28d55U
"""

#This program is a word guessing game

import random

#create ist of words for the user to guess
words = ['software', "python", "mathematics" , "nerds", "twitter", "biology", "deck", "theory"]

#Randomly choose a word from the list
word = random.choice(words)
word

#create 'n' underscores to represent character spaces
spaces = ['_']* len(word)
spaces

#Function that will find all of the letter positions from user guess and if the letter exists, the function will replace the underscore with the correct letter in the correct position(s)

def get_letter_position(guess, word,spaces):
  #create and set index to be -2
  index = -2
  while index != -1:
    #Check if guess/character is in the word, if yes then remove the character from the word and add it to spaces. 
    if guess in word:
      index = word.find(guess)
      #remove letter from the word
      removed_character = '*'
      word = word[:index]+removed_character+word[index+1:]
      spaces[index] = guess
    else: 
      index = -1

  return (word, spaces)

#Create a function to check if the user guessed all of the letters in the word(1 = Yes, -1 = No)
def win_check():
  for i in range(0, len(spaces)):
    if spaces[i] == '_':
      return -1

  return 1

#number of turns for the guess
turns = len(word)+3
for i in range(0,turns):
  #ask for a guess
  guess = input("Guess a character: ")

  if guess in word:
    word, spaces =get_letter_position(guess, word, spaces)
    print (spaces)

  else:
    print("Sorry that letter is not in the word.")
  
  #Check for guess
  if win_check() == 1:
    print("Congratulations! You Win the Game!")
    break

  print ("You have " + str(turns - i) + " turns left")
  print()